# -*- coding: utf-8 -*-
"""3dprinter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ILofTFqLNzj87SViWi75B1JOHvUZPKkI

# 3D Printer DataSet for Mechanical Engineers

Import Data
"""

import pandas as pd
data = pd.read_csv("/content/data.csv")

data.info()

"""Let's multiply these columns by 100 to make them more understandable."""

data.layer_height = data.layer_height*100
data.elongation = data.elongation*100

data.head()

"""In this data set, ABS and PLA assigned 0 and 1 values for materials."""

data.head()

"""#BIVARIATE ANALYSIS

# EFFECT OF FAN SPEED ON TENSION STRENGTH,ROUGHNESS AND ELONGATION for both the materials (ABS/PLA)
"""

import matplotlib.pyplot as plt

import seaborn as sns

plt.figure(figsize=(12,6))
sns.barplot(x='fan_speed', y='tension_strenght', hue='material', data= data)

"""As it is observed from above graph that fan_speed increasing 
then tension_strength is decreasing for abs material.

But for PLA it is observed as the fan speed increases then initially the tensile strength decreases but it (PLA material) shows the strange behavior at speed 75 it shows highest strenght or we can say 75 is optimal fan speed for PLA material.  
"""

plt.figure(figsize=(12,6))
sns.barplot(x='fan_speed', y='roughness', hue='material', data= data)

"""It is clearly observed that both the material roughness increasing as fan speed increases but PLA material has less roughness as compared to fan speed."""

plt.figure(figsize=(12,6))
sns.barplot(x='fan_speed', y='elongation', hue='material', data= data)

"""In abs material elongation increases as the fan speed increases but elongation increases as fan speed increases for PLA material

# EFFECT OF PRINT SPEED ON TENSION STRENGTH,ROUGHNESS AND ELONGATION for both the materials (ABS/PLA)
"""

plt.figure(figsize=(12,6))
sns.barplot(x='print_speed', y='tension_strenght', hue='material', data= data)

"""It is observed that as the print speed increases the tension strength of ABS material is decreasing and for pla material the tension strength increases for PLA material"""

plt.figure(figsize=(12,6))
sns.barplot(x='print_speed', y='roughness', hue='material', data= data)

"""Print speed has no effect on roughness for PLA material but for ABS material as print speed increases the roughness is gradually increases"""

plt.figure(figsize=(12,6))
sns.barplot(x='print_speed', y='elongation', hue='material', data= data)

"""As print speed increases the elongation for both the material decreases.

# EFFECT OF NOZZLE TEMPERATURE ON TENSION STRENGTH,ROUGHNESS AND ELONGATION FOR BOTH THE MATERIAL (ABS/PLA)
"""

sns.scatterplot(data.nozzle_temperature, data.tension_strenght,hue = data.material)

"""*   As we can see here the nozzle temperature for pla mateial ranges from 200 to 220 while for abs ranges 220 to 250, this is obviously due to material as abs required more heat.
*   in pla the tension strength is not much vary with variation of nozzle temperature, but one thing got that with nozzle temperature 215, pla gives max tension strength.
*   in case of abs with increasing nozzle temperature, the strength will be decreases. and abs gives max strength with 220.







"""

sns.scatterplot(data.nozzle_temperature, data.roughness,hue = data.material)

"""
*   in pla the roughness vary with variation of nozzle temperature, and it will be very fine at 220.
*   in case of abs with increasing nozzle temperature, the roughness increases and abs gives fine surface with nozzle temperature 220.






"""

sns.scatterplot(data.nozzle_temperature, data.elongation,hue = data.material)

"""
*   in pla the elongation is not much vary with variation of nozzle temperature, but one thing got that with nozzle temperature around 205, pla gives min variation.
*   in case of abs with increasing nozzle temperature, the elongation will be decreases. and abs gives max variation with 220.






"""

sns.boxplot(x="material", y="nozzle_temperature", data=data)

"""*   From Box plot it is clearly that nozzle temperature are in different ranges as we find in above scatter plots.
*   The median for pla is around 210 while for abs it is around 230.

# Univriate analysis of material with respect to all the relevant parameters
"""

data.columns

"""Let's check behaviour of other parameters like 'layer_height', 'wall_thickness', 'infill_density', 'infill_pattern' on material"""

continuous_columns = ['layer_height', 'wall_thickness', 'infill_density', 'bed_temperature', 'roughness', 'tension_strenght', 'elongation']

for feature in continuous_columns:
    sns.boxplot(x="material", y=feature, data=data)
    # fig,ax = plt.subplots(1,2,figsize=(12,6))
    # ax[0].hist(trip_data[feature])
    # ax[0].set_title('histogram of column values in '+feature)
    # sns.boxplot(trip_data[feature],ax=ax[1])
    # using ax2.set_title for box plot
    # ax[1].set_title('box plot of column values in '+feature)
    # seaborn style setting
    sns.set()
    # matplotlib command for displaying plots
    plt.show()

"""*   if we see from plots their is no change in layer height and bed temperature with respect to material.
*   but in case of wall thickness their is variation, median is higher as compared to pla

* As seen from the above graph that the abs material has higher wall thickness on median basis. but the pla material has higher wall thickness at upper end.

* Infill-density of abs material is much higher than the pla material.

* As it is observed that abs material shows more roughness than pla material.

* Tension_strenght in PLA material is much more than the abs material and so does the elongation.

# Variation of Wall Thickness on Tension strenght of material.
"""

plt.figure(figsize=(12,6))
sns.barplot(x='wall_thickness', y='tension_strenght', hue='material', data= data)

"""* With wall thickness of 9 both the material shows better tension_strength.

# Effect of infill density on various parameter of both the material.
"""

plt.figure(figsize=(12,6))
sns.barplot(x='infill_density', y='tension_strenght', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='infill_density', y='roughness', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='infill_density', y='elongation', hue='material', data= data)

"""* The tension strength of pla material is increases as the infill density increases whereas the abs shows non-uniformity with infill density.

* As observe from the graph roughness of both the material is gradually increases upto infill density of 60 and it drops drastically after that.

* The elongation of pla material is increases as the infill density increases whereas the abs shows non-uniformity with infill density.

# Effect of Infill pattern on various parameter of both the material.
"""

plt.figure(figsize=(12,6))
sns.barplot(x='infill_pattern', y='tension_strenght', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='infill_pattern', y='roughness', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='infill_pattern', y='elongation', hue='material', data= data)

"""* the grid infill pattern shows better results as compared to honeycomb pattern for both the materials

# Effect of layer height on various parameter of both the material.
"""

plt.figure(figsize=(12,6))
sns.barplot(x='layer_height', y='elongation', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='layer_height', y='tension_strenght', hue='material', data= data)

plt.figure(figsize=(12,6))
sns.barplot(x='layer_height', y='roughness', hue='material', data= data)

"""* It is observed that both the material elongation increases as the layer height increases (but the PLA materail has higher elongation as compared to ABS material on same layer_height)

*It is observed that both the material have tension strength increases as the layer height increases (but the PLA materail has higher tension strength as compared to ABS material on same layer_height) and same for roughness.
"""